- name: kubectl | remove metalb config
  become_user: pi
  command: kubectl delete -f /etc/kubernetes/apps/metallb/metallb-conf.yml

- name: kubectl | remove metalb
  become_user: pi
  command: kubectl delete -f /etc/kubernetes/apps/metallb/metallb.yml
