- name: wordpress | delete wordpress ingress
  become_user: pi
  command: kubectl delete -f /etc/kubernetes/apps/wordpress/wordpress-ingress.yml

- name: wordpress | delete wordpress
  become_user: pi
  command: kubectl delete -f /etc/kubernetes/apps/wordpress/wordpress.yml
