---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kreis3-com
  namespace: cert-manager
spec:
  secretName: test-kreis3-com
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: 'test.kreis3.com'
  dnsNames:
  - test.kreis3.com
