---
controller:
#  image:
#    repository: ingress-nginx/ingress-nginx
#    tag: 0.31.1
  ingressClass: nginx-external
  service:
    externalTrafficPolicy: Local
    loadBalancerIP: 192.168.2.201
    name: nginx-external

defaultBackend:
  enabled: false
