---
controller:
#  image:
#    repository: ingress-nginx/ingress-nginx
#    tag: 0.31.1
  ingressClass: nginx-internal
  service:
    externalTrafficPolicy: Local
    loadBalancerIP: 192.168.2.200
    name: nginx-internal
#

defaultBackend:
  enabled: false
