---
controller:
#  image:
#    repository: ingress-nginx/ingress-nginx
#    tag: 0.31.1
  ingressClassResource:
    name: nginx-internal  # default: nginx
    enabled: true
    default: false
    controllerValue: "k8s.io/internal-ingress-nginx"  # default: k8s.io/ingress-nginx

service:
  externalTrafficPolicy: Local
  loadBalancerIP: 192.168.2.200
  name: nginx-internal
#

defaultBackend:
  enabled: false
