---
apiVersion: batch/v1
kind: Job
metadata:
  name: traefik-kv-store
  namespace: kube-system
spec:
  backoffLimit: 3
  activeDeadlineSeconds: 100
  template:
    metadata:
      name: traefik-kv-store
    spec:
      containers:
      - name: storeconfig
        env:
          - name: HOST_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
        image: traefik:v1.7.9
        imagePullPolicy: IfNotPresent
        #args: ["storeconfig", "-c", "/config/traefik.toml", "--consul.endpoint=$(HOST_IP):8500" ]
        args: ["storeconfig", "-c", "/config/traefik.toml", "--consul.endpoint=kreis3-consul-server:8500" ]
        volumeMounts:
        - name: config
          mountPath: /etc/traefik
          readOnly: true
      restartPolicy: Never
      volumes:
      - name: config
        configMap:
          name: traefik-conf-external
