---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-external
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  ingressClassName: nginx-external
  tls:
  - hosts:
    - hello.kreis3.com
    secretName: hello-kreis3-tls
  rules:
  - host: hello.kreis3.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hello
            port:
              number: 80
