---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: hello-exernal
  annotations:
    traefik.frontend.rule.type: PathPrefix
  labels:
    traffic-type: external
spec:
  rules:
  - host: hello.kreis3.com
    http:
      paths:
      - path: /
        backend:
          serviceName: hello
          servicePort: 80
