---
- name: Setup K3s
  hosts: raspberries
  gather_facts: yes
  remote_user: pi
  become: true
  become_method: sudo
  vars_files:
    - config.yml
  roles:
    - K3s

- name: Setup Master
  hosts: master
  gather_facts: yes
  remote_user: pi
  become: true
  become_method: sudo
  vars_files:
    - config.yml
  roles:
    - k3s/master
  tags:
    -k3s-master


- name: Setup Workers
  hosts: slaves
  gather_facts: yes
  remote_user: pi
  become: true
  become_method: sudo
  vars_files:
    - config.yml
  roles:
    - k3s/workers
  tags:
    - k3s-workers
