apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
#networking:
  #podSubnet: "{{ network.pod_subnet }}"
  #serviceSubnet: "{{ network.service_subnet }}"
kubernetesVersion: "v1.17.0"
#apiServer:
#  extraArgs:
    #target-ram-mb: 120
    # max-requests-inflight: 100
scheduler:
  extraArgs:
    leader-elect-lease-duration: 30s
    leader-elect-renew-deadline: 25s
controllerManager:
  extraArgs:
    leader-elect-lease-duration: 30s
    leader-elect-renew-deadline: 25s
#etcd:
#  extraArgs:
    #data-dir: /mnt/pidrive1/kubernetes/etcd
