- name: kubeadm reset
  command: kubeadm reset -f

#- name: Reset data in etcd
#  command: etcdctl rm --recursive registry
#  when: mode == "master"

- name: Remove /var/lib/cni
  file: path=/var/lib/cni state=absent

- name: Remove /etc/cni
  file: path=/etc/cni state=absent

- name: apt | Remove Packages
  apt:
    name: ['kubelet', 'kubeadm', 'kubectl', 'kubernetes-cni']
    force: yes
    state: absent

- name: Delete /etc/kubernetes
  file: path=/etc/kubernetes state=absent

- name: Reboot
  shell: sleep 2 && reboot
  async: 1
  poll: 0
  ignore_errors: true

- name: Waiting for servers
  become: no
  delegate_to: localhost
  wait_for: host={{ inventory_hostname }} port=22 state=started delay=10 timeout=60
