apiVersion: batch/v1
kind: Job
metadata:
  name: backup
  namespace: kube-system
spec:
  # activeDeadlineSeconds: 100
  template:
    metadata:
      name: etcd-backup
    spec:
      containers:
      - name: backup
        # Same image as in /etc/kubernetes/manifests/etcd.yaml
        image: k8s.gcr.io/etcd:3.2.24
        env:
        - name: ETCDCTL_API
          value: "3"
        command: ["/bin/sh"]
        args: ["-c", "etcdctl --endpoints=https://127.0.0.1:2379 --cacert=/etc/kubernetes/pki/etcd/ca.crt --cert=/etc/kubernetes/pki/etcd/healthcheck-client.crt --key=/etc/kubernetes/pki/etcd/healthcheck-client.key snapshot save /backup/etcd-snapshot.db"]
        volumeMounts:
        - mountPath: /etc/kubernetes/pki/etcd
          name: etcd-certs
          readOnly: true
        - mountPath: /backup
          name: backup
      restartPolicy: Never
      nodeSelector:
        kubernetes.io/hostname: pimaster
      tolerations:
      - effect: NoSchedule
        operator: Exists
      hostNetwork: true
      volumes:
      - name: etcd-certs
        hostPath:
          path: /etc/kubernetes/pki/etcd
          type: DirectoryOrCreate
      - name: backup
        hostPath:
          path: /mnt/pidrive1/kubernetes/etcd/backup
          type: DirectoryOrCreate
