---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordpress-exernal
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  ingressClassName: nginx-external
  tls:
  - hosts:
    - kreis3.com
    secretName: kreis3-tls
  rules:
  - host: kreis3.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wordpress
            port:
              number: 80
