---
#- name: install metallb
#  import_tasks: metallb.yml
#  when: mode == "master"

- name: install nfs support
  import_tasks: nfs.yml
  when: mode == "master"

- name: test nfs support
  import_tasks: nfs-test.yml
  when: mode == "master"

#- name: install dashboard
#  import_tasks: dashboard.yml
#  when: mode == "master"
