- name: Create dir /etc/kubernetes/apps/secrets
  file: path=/etc/kubernetes/apps/secrets state=directory mode=0775

- name: secrets | copy namespace definition
  template: src=secrets.yml dest=/etc/kubernetes/apps/secrets

- name: secrets | load secrets
  become_user: pi
  command: kubectl apply -f /etc/kubernetes/apps/secrets/secrets.yml
