- name: Create dir /etc/kubernetes/apps/traefik-external
  file: path=/etc/kubernetes/apps/traefik-external state=directory mode=0775

- name: traefik-external kv | copy configmap
  template: src=traefik-external-configmap.yml dest=/etc/kubernetes/apps/traefik-external

- name: traefik-external kv | copy key value job
  template: src=traefik-external-storekv.yml dest=/etc/kubernetes/apps/traefik-external

- name: traefik-external kv | apply configmap
  become_user: pi
  command: kubectl apply -f /etc/kubernetes/apps/traefik-external/traefik-external-configmap.yml

- name: traefik-external kv | store config in key-value store
  become_user: pi
  command: kubectl apply -f /etc/kubernetes/apps/traefik-external/traefik-external-storekv.yml

- pause:
    seconds: 30

- name: traefik-external kv | remove job
  become_user: pi
  command: kubectl delete -f /etc/kubernetes/apps/traefik-external/traefik-external-storekv.yml
