- name: Create dir /etc/kubernetes/apps/traefik-external
  file: path=/etc/kubernetes/apps/traefik-external state=directory mode=0775

- name: traefik-external | copy configmap
  template: src=traefik-external-configmap.yml dest=/etc/kubernetes/apps/traefik-external

- name: traefik-external | copy deployment
  template: src=traefik-external-deployment.yml dest=/etc/kubernetes/apps/traefik-external

- name: traefik-external | copy service
  template: src=traefik-external-service.yml dest=/etc/kubernetes/apps/traefik-external

- name: traefik-external | apply configmap
  become_user: pi
  command: kubectl apply -f /etc/kubernetes/apps/traefik-external/traefik-external-configmap.yml

- name: traefik-external | apply deployment
  become_user: pi
  command: kubectl apply -f /etc/kubernetes/apps/traefik-external/traefik-external-deployment.yml

- name: traefik-external | apply service
  become_user: pi
  command: kubectl apply -f /etc/kubernetes/apps/traefik-external/traefik-external-service.yml
