
- name: Install https dependencies
  apt:
    name: ['ca-certificates', 'software-properties-common']
    update_cache: yes
    state: present
    allow_unauthenticated: yes
  tags:
    - apt


#- name: Add Kubernetes Repo Key
#  apt_key: url=https://packages.cloud.google.com/apt/doc/apt-key.gpg

#- name: Add Kubernetes Repo
  # Try to pick up latest stable builds. Switch over to '-unstable' if targeting latest releases
#  apt_repository: repo='deb http://apt.kubernetes.io/ kubernetes-xenial main' state=present

#- name: Add Docker Repo Key
#  apt_key: url=https://download.docker.com/linux/raspbian/gpg

#- name: Add Docker Repo
#  apt_repository: repo='deb [arch=armhf] https://download.docker.com/linux/raspbian stretch stable'

- name: Update APT package cache and upgrade
  apt:
    update_cache: yes
    autoremove: yes
    upgrade: yes
  tags:
    - apt

- name: Install Packages
  apt:
    name: ['iperf', 'mtr-tiny', 'bridge-utils', 'socat', 'jq', 'vim', 'htop', 'python-pexpect-doc', 'haveged', 'python3-pip', 'git', 'iptables']
    force: yes
    allow_unauthenticated: yes
    state: present
  tags:
    - apt