- name: Activating cgroup
  lineinfile:
    path: /boot/cmdline.txt
    backrefs: true
#    regexp: '^(.*plymouth.ignore-serial-consoles)$'
    regexp: '(.*rootwait)$'
    line: '\1  cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
