- name: mysql| Create dir /etc/kubernetes/apps/mysql
  file: path=/etc/kubernetes/apps/mysql state=directory mode=0775

- name: mysql | copy mysql definition
  template: src=mysql.yml dest=/etc/kubernetes/apps/mysql

- name: myslq | load mysql
  become_user: pi
  environment:
    KUBECONFIG: /home/pi/.kube/config
  command: kubectl apply -f /etc/kubernetes/apps/mysql/mysql.yml
