- name: sqlsecrets | Create dir /etc/kubernetes/apps/sqlsecrets
  file: path=/etc/kubernetes/apps/sqlsecrets state=directory mode=0775

- name: sqlsecrets | copy secret definition
  template: src=sqlsecrets.yml dest=/etc/kubernetes/apps/sqlsecrets

- name: sqlsecrets | load secrets
  become_user: pi
  command: kubectl apply -f /etc/kubernetes/apps/sqlsecrets/sqlsecrets.yml
